/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_YRwindowajouterETS (void);
GtkWidget* create_YRwindowtreeview (void);
GtkWidget* create_MT_w_acceuil (void);
GtkWidget* create_MT_w_formulaire (void);
GtkWidget* create_MT_w_liste (void);
GtkWidget* create_MT_w_rdv (void);
GtkWidget* create_MT_w_m_formulaire (void);
GtkWidget* create_AHwindowajouter (void);
GtkWidget* create_AHwindowtreeview (void);
GtkWidget* create_Acceuil (void);
GtkWidget* create_login (void);
GtkWidget* create_OGajout (void);
GtkWidget* create_OGaffiche (void);
GtkWidget* create_fenetre_ajout (void);
GtkWidget* create_fenetre_afficher (void);
GtkWidget* create_fenetre_modifier (void);
GtkWidget* create_fenetre_supprimer (void);
GtkWidget* create_fenetre_rechercher (void);
GtkWidget* create_fenetre_calcul (void);
GtkWidget* create_rdvs (void);
